import css from './About.module.css';
import layerMobile from '../../assets/Layer-Mobile.png';
import layerTablet from '../../assets/Layer-Tablet.png';
import layerMedium from '../../assets/Layer-Medium.png';
import layerDesktop from '../../assets/Layer-Desctop.png';
import { ReactComponent as NameIcon } from '../../assets/addsharp.svg';
import useMediaQuery from 'helpers/useMediaQuery';
import Banner from 'components/About/Banner/Banner';

function About() {
  const isMobile = useMediaQuery('(max-width:767px)');
  const isTablet = useMediaQuery('(max-width:1279px)');
  const isMedium = useMediaQuery('(max-width:1439px)');

  return (
    <>
      <section id="about" className="container">
        {isMobile ? (
          <>
            <h2 className={css.title}>
              A story that
              <br />
              started
              <br />
              with
              <span>
                &nbsp;one
                <br />
                simple
                <br />
                ape
              </span>
            </h2>
            <p className={`information ${css.information}`}>
              Who got
              <br />
              fed up with boring and hypocritic commonplace this is how the idea
              of escaping and dynamic journey on the yacht
            </p>
            <div className={css.icon}>
              <NameIcon />
            </div>
            <p className={`description ${css.description}`}>
              Each artwork in the collection tells a story of one journey. Arts
              are randomly generated by users
            </p>
            <img width={216} height={292} src={layerMobile} alt="layerMobile" />
          </>
        ) : (
          <div className={css.flex}>
            <div>
              <h2 className={css.title}>
                A story that started with <span>one simple ape</span>
              </h2>
              <div className={css.icon}>
                <NameIcon />
                <p className={`description ${css.description}`}>
                  Each artwork in the collection tells a story of one journey.
                  Arts are randomly generated by users
                </p>
              </div>
            </div>
            <div>
              <p className={`information ${css.information}`}>
                Who got fed up with boring and hypocritic commonplace this is
                how the idea of escaping and dynamic journey on the
                <br />
                yacht
              </p>
              {isTablet ? (
                <img
                  width={313}
                  height={422}
                  src={layerTablet}
                  alt="layerTablet"
                />
              ) : isMedium ? (
                <img
                  width={492}
                  height={662}
                  src={layerMedium}
                  alt="layerMedium"
                />
              ) : (
                <img
                  width={610}
                  height={822}
                  src={layerDesktop}
                  alt="layerDesktop"
                />
              )}
            </div>
          </div>
        )}
      </section>
      <Banner>
        <div>Destroy stereotypes</div>
        <NameIcon />
        <div>HAVE NO LIMITS</div>
        <NameIcon />
        <div>Break rules</div>
        <NameIcon />
      </Banner>
    </>
  );
}

export default About;
